spring:
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
    driver-class-name: ${JDBC_DRIVER}
  jooq:
    sql-dialect: ${JOOQ_SQL_DIALECT}
  graphql:
    cors:
      allowed-origins:
        - https://studio.apollographql.com #remove if you are not using Apollo Studio
        - ${FRONT_END_URL}
cta:
  train-api-key: ${TRAIN_API_KEY}
rollbar:
  access-token: ${ROLLBAR_ACCESS_TOKEN}
  environment: ${ROLLBAR_ENVIRONMENT}
